# docker-compose.yml
#
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ghalass2-container-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/www:/var/www/certbot  # <== important
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/certbot --email support@ghalass.com --agree-tos --no-eff-email --non-interactive --keep-until-expiring -d home.ghalass.com -d www.home.ghalass.com


