# docker-compose.yml
# services:
#   nginx:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: ghalass2-container-nginx
#     restart: unless-stopped
#     ports:
#       - "80:80"
#       - "443:443"


services:
  nginx:
    image: nginx:alpine
    container_name: ghalass2-container-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - webroot:/var/www/html
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email support@ghalass.com --agree-tos --no-eff-email --non-interactive --keep-until-expiring -d main.ghalass.com
