# docker-compose.yml
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ghalass2-container-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"